jdbcSettings:
  url: "jdbc:postgresql://localhost:5432/rickylazuardy"
  username: "rickylazuardy"
  password: "rolazuardy234"
  driverClassName: "org.postgresql.Driver"

packageName: "id.web.noxymon.concurrentspringboot.repositories.entities"
tableScanMode: 'RuleBased'
tableScanRules:
 - tableNames: ["usage_counter","usage_detail","usage_fail_detail"]