jdbcSettings:
  url: "jdbc:postgresql://172.20.0.2:5432/db_test"
  username: "master"
  password: "12345678"
  driverClassName: "org.postgresql.Driver"

packageName: "id.web.noxymon.concurrentspringboot.repositories.entities"
tableScanMode: 'RuleBased'
tableScanRules:
 - tableNames: ["usage_counter"]